export const news = [
  { id: '1', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/carteirinha.png'), description: 'Ola 1', data: '11' },
  { id: '2', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/calendario.png'), description: 'Conteudo da noticia', data: '' },
  { id: '3', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/teste.png'), description: 'Ola 3', data: '' },
  { id: '4', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/carteirinha.png'), description: 'Ola 4', data: '' },
  { id: '5', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/teste.png'), description: 'Ola 5', data: '' },
  { id: '6', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/teste.png'), description: 'Ola 6', data: '' },
  { id: '7', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/teste.png'), description: 'Ola 7', data: '' },
  { id: '8', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/teste.png'), description: 'Ola 8', data: '' },
  { id: '9', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/teste.png'), description: 'Ola 8', data: '' },
  { id: '10', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/teste.png'), description: 'Ola 8', data: '' },
  { id: '11', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/teste.png'), description: 'Ola 8', data: '' },
  { id: '12', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/teste.png'), description: 'Ola 8', data: '' },
  { id: '13', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/carteirinha.png'), description: 'Ola 4', data: '' },
  { id: '14', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/carteirinha.png'), description: 'Ola 4', data: '' },
  { id: '15', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/carteirinha.png'), description: 'Ola 4', data: '' },
  { id: '16', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/carteirinha.png'), description: 'Ola 4', data: '' },
  { id: '17', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/carteirinha.png'), description: 'Ola 4', data: '' },
  { id: '18', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/carteirinha.png'), description: 'Ola 4', data: '' },
  { id: '19', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/carteirinha.png'), description: 'Ola 4', data: '' },
  { id: '20', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/carteirinha.png'), description: 'Ola 4', data: '' },
  { id: '21', title: 'Nome do Evento fim', icon: require('../assets/ScrollMenuIcons/calendario.png'), description: 'Ola 2', data: '' },
]