export const news = [
  { id: '1', type: 'Date', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/carteirinha.png'), description: 'Ola 1', data: '2021-09-08T06:07' },
  { id: '2', type: 'Text', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/calendario.png'), description: 'Conteudo da noticia', data: '' },
  { id: '3', type: 'Text', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/teste.png'), description: 'Conteudo da noticia', data: '2021-09-08T06:07' },
  { id: '4', type: 'Date', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/carteirinha.png'), description: 'Ola 4', data: '2021-09-08T06:07' },
  { id: '5', type: 'Text', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/teste.png'), description: 'Conteudo da noticia', data: '' },
  { id: '6', type: 'Text', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/teste.png'), description: 'Ola 6', data: '' },
  { id: '7', type: 'Text', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/teste.png'), description: 'Ola 7', data: '' },
  { id: '8', type: 'Text', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/teste.png'), description: 'Ola 8', data: '' },
  { id: '9', type: 'Text', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/teste.png'), description: 'Ola 8', data: '' },
  { id: '10', type: 'Text', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/teste.png'), description: 'Ola 8', data: '' },
  { id: '11', type: 'Text', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/teste.png'), description: 'Ola 8', data: '' },
  { id: '12', type: 'Text', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/teste.png'), description: 'Ola 8', data: '' },
  { id: '13', type: 'Text', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/carteirinha.png'), description: 'Ola 4', data: '' },
  { id: '14', type: 'Text', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/carteirinha.png'), description: 'Ola 4', data: '' },
  { id: '15', type: 'Text', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/carteirinha.png'), description: 'Ola 4', data: '' },
  { id: '16', type: 'Text', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/carteirinha.png'), description: 'Ola 4', data: '' },
  { id: '17', type: 'Text', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/carteirinha.png'), description: 'Ola 4', data: '' },
  { id: '18', type: 'Text', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/carteirinha.png'), description: 'Ola 4', data: '' },
  { id: '19', type: 'Text', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/carteirinha.png'), description: 'Ola 4', data: '' },
  { id: '20', type: 'Text', title: 'Nome do Evento', icon: require('../assets/ScrollMenuIcons/carteirinha.png'), description: 'Ola 4', data: '' },
  { id: '21', type: 'Text', title: 'Nome do Evento fim', icon: require('../assets/ScrollMenuIcons/calendario.png'), description: 'Ola 2', data: '' },
]